#include "testApp.h"

#define MAX_LEDS 96
#define UI_HEIGHT 100
#define TEMPLATE_PLACEHOLDER "$INSERT_IMAGE_DATA_HERE$"
#define TEMPLATE_HEADER "// Image data generated by KronosSimulator.app"

void testApp::setup(){
	
	currentFramerate = 8;
	ofSetFrameRate(currentFramerate);
	
	int guih = ofGetHeight() - 30;
	openButton.setup("open animation",300);
	openButton.setPosition(10,guih);
	openButton.addListener(this,&testApp::onOpenClicked);

	saveButton.setup("save",300);
	saveButton.setPosition(150,guih);
	saveButton.addListener(this,&testApp::onSaveClicked);
	
	frameRateSlider.setup("framerate", currentFramerate, 1, 60);
	frameRateSlider.setPosition(500,guih);
	frameRateSlider.addListener(this,&testApp::onFramerateChanged);
	
	ofBackgroundHex(0x000000);
	image_loaded = false;
}

void testApp::update(){}

void testApp::draw() {
	
	// draw gui - persistent
	openButton.draw();
	
	// draw animation
	if (image_loaded){
		
		// draw gui - widgets shown only with anim loaded
		saveButton.draw();
		frameRateSlider.draw();
		
		// draw info string
		stringstream s;
		s
		<< loaded_image_name
		<< "\n"
		<< "using " << num_leds << " leds. "
		<< "frame " << current_frame << "/" << num_frames;
		ofSetHexColor(0x666666);
		ofDrawBitmapString(s.str(), 10, 20);
		
		
		ofPushMatrix();
		ofTranslate(10, 80);
	
		for(int pixel = 0; pixel < num_leds; pixel++) {
			ofSetColor(loadedImage.getColor(pixel,current_frame));
			ofRect(0,0,led_w,led_h);
			ofTranslate(led_w + led_spacing, 0);
		}
	
		ofPopMatrix();
	
		// wind on counter
		current_frame++;
		if (current_frame >= num_frames) current_frame = 0;
	}
}

void testApp::saveFileToSelection(ofFileDialogResult saveFileResult){
	
	// step 1 - build a string representation of the image data
	stringstream s;
	s
	<< TEMPLATE_HEADER << "\n"
	<< "// file: " << loaded_image_name << "\n"
	<< "// generated at " << ofGetTimestampString() << "\n\n\n"
	<< "#define N_FRAMES " << num_frames << "\n"
	<< "#define N_PIXELS " << num_leds << "\n\n"
	<< "const char frames[N_FRAMES][N_PIXELS][3] = {";
	for(int frame = 0; frame < num_frames; frame++) {
		if (frame != 0) s << ",";
		s << "{";
		for(int pixel = 0; pixel < num_leds; pixel++) {
			if (pixel != 0) s << ",";
			ofColor c = loadedImage.getColor(pixel,frame);
			// int r = 16711680;
			int r = c.r;
			int g = c.g;
			int b = c.b;
			// s << "pixel " << pixel << " red: " << r << ", green: " << g << ", blue: " << g << "\n";
			s << "{" << r << "," << g << "," << b << "}";
		}
		s << "}";
	}
	s << "}; \n\n";
	
	// step 2 - load a boilerplate arduino sketch
	ofBuffer buffer = ofBufferFromFile("arduino_template/arduino_template.ino");
	if(buffer.size()) {
		// step 3 - insert the image data into the arduino sketch
		string arduino_template = buffer.getText();
		ofStringReplace(arduino_template,TEMPLATE_PLACEHOLDER,s.str());
		buffer.set(arduino_template);
		// step 4 - save the file
		ofBufferToFile(saveFileResult.getPath(), buffer);
	}
}
	
void testApp::processOpenFileSelection(ofFileDialogResult openFileResult){
	
	ofFile file (openFileResult.getPath()); 
	
	if (file.exists()){
		image_loaded = false;
		loaded_image_name = file.getFileName();
		string fileExtension = ofToUpper(file.getExtension());
		if (fileExtension == "JPG" || fileExtension == "PNG") {
			loadedImage.loadImage(openFileResult.getPath());
			num_leds = loadedImage.getWidth();
			if (num_leds <= MAX_LEDS){
				if (num_leds <= 32){
					led_spacing = 3;
					led_h = 30;
					led_w = 30;
				}
				if (num_leds > 32){
					led_spacing = 2;
					led_h = 16;
					led_w = 16;
				}
				if (num_leds > 64){
					led_spacing = 1;
					led_h = 11;
					led_w = 11;
				}
				num_frames = loadedImage.getHeight();
				current_frame = 0;
				image_loaded = true;
			}
		}
	}
	
}

void testApp::onOpenClicked(bool & pressed){
	if (pressed == false) return;
	ofFileDialogResult openFileResult= ofSystemLoadDialog("Select a jpg or png");
	processOpenFileSelection(openFileResult);
}

void testApp::onSaveClicked(bool & pressed){
	if (pressed == false) return;
	ofFileDialogResult saveFileResult = ofSystemSaveDialog(loaded_image_name + ".ino", "Save to file");
	if (saveFileResult.bSuccess) saveFileToSelection(saveFileResult);
}

void testApp::onFramerateChanged(int & rate){
	ofSetFrameRate(rate);
}
